services:
  main:
    build: ./To_Do_List
    command: ./runserver.sh
    volumes:
      - ./To_Do_List:/usr/src/main
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    ports:
      - 5432:5432

volumes:
  postgres_data: